# Generated by Django 2.1.7 on 2020-07-28 13:28

from django.db import migrations, models
import django.db.models.deletion
import subUnit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUnitModel',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=10000)),
                ('image', models.FileField(upload_to=subUnit.models.upload_path)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_subunit', to='unit.UnitModel')),
            ],
        ),
    ]
