# Generated by Django 2.1.7 on 2020-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('gradeId', models.AutoField(primary_key=True, serialize=False)),
                ('gradeTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
