# Generated by Django 2.1.7 on 2020-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ('label',)},
        ),
        migrations.RemoveField(
            model_name='examdescribequestionmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='examdescribequestionmodel',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
    ]
