# Generated by Django 2.1.7 on 2020-07-31 19:25

from django.db import migrations, models
import models_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='pdf',
            field=models.FileField(default=1, upload_to=models_app.models.upload_path),
            preserve_default=False,
        ),
    ]
