# Generated by Django 2.1.7 on 2020-08-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_auto_20200806_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examchoicequestionmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_choice', to='models_app.CategoryModel'),
        ),
    ]
