# Generated by Django 2.1.7 on 2020-08-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_auto_20200806_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examblankspacequestionmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_blank', to='models_app.SubjectModel'),
        ),
        migrations.AlterField(
            model_name='examdescribequestionmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_describe', to='models_app.SubjectModel'),
        ),
        migrations.AlterField(
            model_name='matchinginstructionmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_instruction', to='models_app.SubjectModel'),
        ),
    ]
