# Generated by Django 2.1.7 on 2020-08-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_auto_20200806_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_unit', to='models_app.CategoryModel'),
        ),
    ]
