# Generated by Django 2.1.7 on 2020-08-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_auto_20200806_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examchoicequestionmodel',
            old_name='subject',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='examblankspacequestionmodel',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examdescribequestionmodel',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='matchinginstructionmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='examblankspacequestionmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_blank', to='models_app.CategoryModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examdescribequestionmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_describe', to='models_app.CategoryModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchinginstructionmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_instruction', to='models_app.CategoryModel'),
            preserve_default=False,
        ),
    ]
