# Generated by Django 2.1.7 on 2020-08-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_auto_20200806_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizematchquestionmodel',
            name='unit',
        ),
        migrations.AlterField(
            model_name='quizeblankspacequestionmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_blank', to='models_app.UnitModel'),
        ),
        migrations.AlterField(
            model_name='quizechoicequestionmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_choice', to='models_app.UnitModel'),
        ),
        migrations.AlterField(
            model_name='quizedescribequestionmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_describe', to='models_app.UnitModel'),
        ),
        migrations.DeleteModel(
            name='QuizeMatchQuestionModel',
        ),
    ]
